### ISSUE TITLE
Impossible get subdivisions

### ISSUE THREAD

**Issue by sVIKs** [brigadier/geodata2#1]
From GeoIP2-City.mmdb I need subdivisions. I use next line 
{subdivisions, [<<"subdivisions">>, <<"names">>, <<"en">>], <<>>},
but subdivisions is list of proplist 
[{<<"subdivisions">>, [[{<<"names">>, [{<<"en">>, <<"....">>}]}]]}]
so i get <<>>

**Comment by brigadier** [comment]
I'll have a look in a couple of days

**Comment by brigadier** [comment]
hi,
please check the newest version 1.1.2, it now allows deep schema for proplist data. See the `test_deepchema` test as an example. Please let me know if it works for you.

Side note: it was possible to get subdivisions prior to this change with just `{subdivisions, [<<"subdivisions">>], <<>>}` and parse the deep list in the calling code.

**Comment by sVIKs** [comment]
Thanks.

I have another question. 
Are project support DAT format?

**Comment by brigadier** [comment]
Hi,
No, it does not support legacy format. As far as I know there's no documentation for the old format. So MMDB only.
